spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stats_bot
    username: postgres
    password: gfhjkmvjq
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

bot:
  name: Doceho
  token: 5679759748:AAGr5sBCEWfoWaaFVzrdqJfsSOel26NpfM4
