spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/stats_bot
    username: postgres
    password: gfhjkmvjq
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  sql:
    init:
      mode: always

bot:
  name: Doceho
  token: 5679759748:AAGr5sBCEWfoWaaFVzrdqJfsSOel26NpfM4

leetify:
  login: alekspavlov02@mail.ru
  password: gfhjkmvjq