spring:
  config:
    import: "optional:classpath:application-secrets.yaml"
  datasource:
    url: jdbc:postgresql://localhost:5434/stats_bot
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

bot:
  name: Doceho

leetify: {}
